name: ec2-creation
# When to trigger this pipeline. We can trigger on push or manual or someother events like creating PR, updating PR, creating branches, creating issues
on: [push] # triggers
jobs: # Pipeline. One workflow can have multiple pipelines
  terraform:
    runs-on: ubuntu-latest # Linux OS. We can have windows or MAC
    steps: # stages
      - name: chechout the code 
        uses: actions/checkout@v5
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: terraform init
        run: terraform init
      - name: terraform validate
        run: terraform validate
       # 2. Authenticate with AWS using your GitHub Secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Change to your preferred AWS region
      - name: terraform plan
        run: terraform plan

      - name: terraform apply
        run: terraform destroy -auto-approve
